configurationVariables:
  jdbcfunc.SAPTxStore.failFastMode: 'false'
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
info:
  model: int-scaffold
packages:
- gitBranch: release/1.0.0
  gitServerName: GH_SK
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  name: ProjectVersionProject
version: 1.0.0
